version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PGHOST: host
      SYNCHRONIZE_DATABASE: true
    env_file:
      - .env
    volumes:
      - ./:/usr/app
    depends_on:
      - database
    ports:
      - 3000:5000

  database:
    image: postgres:14.4-alpine
    container_name: camagru-database
    env_file:
      - .env
    volumes:
      - ./src/database/camagru.sql:/docker-entrypoint-initdb.d/camagru.sql